[package]
name = "aoc_rust2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
regex = "1.11.1"
gcd = "2.3.0"
num = "0.4.3"